import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.scanQR': 'Scan QR',
    'nav.equipment': 'Equipment',
    'nav.locations': 'Locations',
    'nav.vehicles': 'Vehicles',
    'nav.workOrders': 'Work Orders',
    'nav.schedules': 'Schedules',
    'nav.checklists': 'Checklists',
    'nav.procedures': 'Procedures',
    'nav.reports': 'Reports',
    'nav.partsInventory': 'Parts Inventory',
    'nav.manual': 'User Manual',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.loading': 'Loading...',
    'common.actions': 'Actions',
    'common.view': 'View',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.total': 'Total',
    'common.all': 'All',
    'common.created': 'Created',
    'common.noResults': 'No results found',
    
    // Equipment
    'equipment.title': 'Equipment',
    'equipment.subtitle': 'total equipment',
    'equipment.add': 'Add Equipment',
    'equipment.import': 'Import Excel',
    'equipment.inventoryNumber': 'Nr. Inventar',
    'equipment.name': 'Name',
    'equipment.brand': 'Brand',
    'equipment.model': 'Model',
    'equipment.serialNumber': 'Serial Number',
    'equipment.location': 'Location',
    'equipment.purchaseDate': 'Purchase Date',
    'equipment.status': 'Status',
    'equipment.operational': 'Operational',
    'equipment.maintenance': 'Maintenance',
    'equipment.retired': 'Retired',
    'equipment.details': 'Details',
    'equipment.noEquipment': 'No equipment found',
    'equipment.searchPlaceholder': 'Search equipment by name, serial number, or model...',
    
    // Work Orders
    'workOrders.title': 'Work Orders',
    'workOrders.subtitle': 'Manage maintenance requests and tasks',
    'workOrders.new': 'New Work Order',
    'workOrders.all': 'All Orders',
    'workOrders.open': 'Open',
    'workOrders.inProgress': 'In Progress',
    'workOrders.onHold': 'On Hold',
    'workOrders.completed': 'Completed',
    'workOrders.cancelled': 'Cancelled',
    'workOrders.priority': 'Priority',
    'workOrders.low': 'Low',
    'workOrders.medium': 'Medium',
    'workOrders.high': 'High',
    'workOrders.critical': 'Critical',
    'workOrders.searchPlaceholder': 'Search work orders...',
    'workOrders.allPriority': 'All Priority',
    'workOrders.noWorkOrdersFound': 'No work orders found',
    'workOrders.noWorkOrdersYet': 'No work orders yet',
    'workOrders.tryAdjustingFilters': 'Try adjusting your filters',
    'workOrders.createFirstWorkOrder': 'Create your first work order to get started',
    'workOrders.urgent': 'URGENT',
    'workOrders.highPriority': 'High Priority',
    'workOrders.equipment': 'Equipment:',
    'workOrders.location': 'Location:',
    'workOrders.assignedTo': 'Assigned to:',
    'workOrders.type': 'Type',
    'workOrders.corrective': 'Corrective',
    'workOrders.preventive': 'Preventive',
    'workOrders.inspection': 'Inspection',
    
    // Maintenance Schedules
    'schedules.title': 'Maintenance Schedules',
    'schedules.subtitle': 'Manage preventive maintenance schedules',
    'schedules.new': 'New Schedule',
    'schedules.all': 'All Schedules',
    'schedules.active': 'Active',
    'schedules.overdue': 'Overdue',
    'schedules.dueThisWeek': 'Due This Week',
    'schedules.frequency': 'Frequency',
    'schedules.daily': 'Daily',
    'schedules.weekly': 'Weekly',
    'schedules.monthly': 'Monthly',
    'schedules.quarterly': 'Quarterly',
    'schedules.semiannually': 'Semi-annually',
    'schedules.annually': 'Annually',
    'schedules.nextDue': 'Next Due',
    'schedules.lastCompleted': 'Last completed',
    'schedules.complete': 'Complete',
    'schedules.pause': 'Pause',
    'schedules.resume': 'Resume',
    'schedules.showCompleted': 'Show Completed Only',
    'schedules.additionalFilters': 'Additional Filters:',
    
    // Checklists
    'checklists.title': 'Checklist Templates',
    'checklists.subtitle': 'Create and manage reusable checklist templates',
    'checklists.new': 'New Template',
    'checklists.items': 'checklist items',
    'checklists.noTemplates': 'No templates yet',
    'checklists.createFirst': 'Create your first checklist template to use in maintenance schedules',
    'checklists.templateName': 'Template Name',
    'checklists.addItem': 'Add Item',
    
    // Procedures
    'procedures.title': 'Procedure Templates',
    'procedures.subtitle': 'Create and manage step-by-step procedures with images',
    'procedures.new': 'New Template',
    'procedures.steps': 'steps',
    'procedures.noProcedures': 'No templates yet',
    'procedures.createFirst': 'Create your first procedure template with step-by-step instructions',
    'procedures.addStep': 'Add Step',
    'procedures.hasImage': 'Has image',
    
    // Locations
    'locations.title': 'Locations',
    'locations.subtitle': 'Manage facility locations',
    'locations.new': 'New Location',
    'locations.add': 'Add Location',
    'locations.building': 'Building',
    'locations.floor': 'Floor',
    'locations.room': 'Room',
    'locations.address': 'Address',
    'locations.noLocations': 'No locations found',
    'locations.noLocationsYet': 'No locations yet',
    'locations.searchPlaceholder': 'Search locations...',
    'locations.tryAdjustingSearch': 'Try adjusting your search',
    'locations.getStarted': 'Get started by adding your first location',
    'locations.deleteConfirm': 'Are you sure you want to delete',
    
    // Vehicles
    'vehicles.title': 'Vehicles',
    'vehicles.subtitle': 'Manage company vehicles',
    'vehicles.new': 'New Vehicle',
    'vehicles.add': 'Add Vehicle',
    'vehicles.brand': 'Brand',
    'vehicles.model': 'Model',
    'vehicles.registrationNumber': 'Registration Number',
    'vehicles.vin': 'VIN',
    'vehicles.year': 'Year',
    'vehicles.color': 'Color',
    'vehicles.fuelType': 'Fuel Type',
    'vehicles.transmission': 'Transmission',
    'vehicles.engineCapacity': 'Engine Capacity (cc)',
    'vehicles.powerHP': 'Power (HP)',
    'vehicles.currentMileage': 'Current Mileage (km)',
    'vehicles.assignedTo': 'Assigned To',
    'vehicles.department': 'Department',
    'vehicles.purchaseDate': 'Purchase Date',
    'vehicles.purchasePrice': 'Purchase Price',
    'vehicles.status': 'Status',
    'vehicles.operational': 'Operational',
    'vehicles.inService': 'In Service',
    'vehicles.broken': 'Broken',
    'vehicles.sold': 'Sold',
    'vehicles.retired': 'Retired',
    'vehicles.noVehicles': 'No vehicles found',
    'vehicles.searchPlaceholder': 'Search vehicles...',
    'vehicles.documents': 'Documents',
    'vehicles.insurance': 'Insurance',
    'vehicles.vignette': 'Vignette',
    'vehicles.repairs': 'Repairs',
    'vehicles.rca': 'RCA Insurance',
    'vehicles.casco': 'CASCO Insurance',
    'vehicles.currentInsurance': 'Current Insurance',
    'vehicles.insuranceHistory': 'Insurance History',
    'vehicles.currentVignette': 'Current Vignette',
    'vehicles.vignetteHistory': 'Vignette History',
    'vehicles.repairHistory': 'Repair History',
    'vehicles.addDocument': 'Add Document',
    'vehicles.addInsurance': 'Add Insurance',
    'vehicles.addVignette': 'Add Vignette',
    'vehicles.addRepair': 'Add Repair',
    'vehicles.documentType': 'Document Type',
    'vehicles.insuranceCompany': 'Insurance Company',
    'vehicles.policyNumber': 'Policy Number',
    'vehicles.startDate': 'Start Date',
    'vehicles.endDate': 'End Date',
    'vehicles.premiumAmount': 'Premium Amount',
    'vehicles.vignetteType': 'Vignette Type',
    'vehicles.serialNumber': 'Serial Number',
    'vehicles.country': 'Country',
    'vehicles.price': 'Price',
    'vehicles.repairType': 'Repair Type',
    'vehicles.repairDate': 'Repair Date',
    'vehicles.serviceProvider': 'Service Provider',
    'vehicles.serviceLocation': 'Service Location',
    'vehicles.mileageAtRepair': 'Mileage at Repair',
    'vehicles.laborCost': 'Labor Cost',
    'vehicles.partsCost': 'Parts Cost',
    'vehicles.totalCost': 'Total Cost',
    'vehicles.benzina': 'Gasoline',
    'vehicles.motorina': 'Diesel',
    'vehicles.electric': 'Electric',
    'vehicles.hibrid': 'Hybrid',
    'vehicles.gpl': 'LPG',
    'vehicles.manuala': 'Manual',
    'vehicles.automata': 'Automatic',
    'vehicles.preventiva': 'Preventive',
    'vehicles.corectiva': 'Corrective',
    'vehicles.accident': 'Accident',
    'vehicles.revizie': 'Service',
    'vehicles.certificat_inmatriculare': 'Registration Certificate',
    'vehicles.procura': 'Power of Attorney',
    'vehicles.contract_vanzare': 'Sales Contract',
    'vehicles.other': 'Other',
    'vehicles.7_zile': '7 Days',
    'vehicles.1_luna': '1 Month',
    'vehicles.3_luni': '3 Months',
    'vehicles.1_an': '1 Year',
    'vehicles.active': 'Active',
    'vehicles.expired': 'Expired',
    'vehicles.noDocuments': 'No documents found',
    'vehicles.noInsurance': 'No insurance found',
    'vehicles.noVignettes': 'No vignettes found',
    'vehicles.noRepairs': 'No repairs found',
    'vehicles.uploadFile': 'Upload File',
    'vehicles.notes': 'Notes',
    'vehicles.issueDate': 'Issue Date',
    'vehicles.expiryDate': 'Expiry Date',
    'vehicles.scheduled': 'Scheduled',
    'vehicles.inProgress': 'In Progress',
    'vehicles.completed': 'Completed',
    'vehicles.cancelled': 'Cancelled',
    'vehicles.expiresIn': 'Expires in',
    'vehicles.expiredDaysAgo': 'Expired',
    'vehicles.days': 'days',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'System Overview',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.upcomingMaintenance': 'Upcoming Maintenance',
    
    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.selectLanguage': 'Select Language',
    'settings.english': 'English',
    'settings.romanian': 'Romanian',
    
    // Work Order Detail
    'workOrderDetail.notFound': 'Work order not found',
    'workOrderDetail.backToList': 'Back to Work Orders',
    'workOrderDetail.reassign': 'Reassign',
    'workOrderDetail.edit': 'Edit',
    'workOrderDetail.delete': 'Delete',
    'workOrderDetail.description': 'Description',
    'workOrderDetail.noDescription': 'No description provided',
    'workOrderDetail.photos': 'Photos',
    'workOrderDetail.reportPhoto': 'Report Photo',
    'workOrderDetail.issuePhoto': 'Issue Photo',
    'workOrderDetail.completionPhoto': 'Completion Photo',
    'workOrderDetail.noPhotosYet': 'No photos attached yet',
    'workOrderDetail.equipment': 'Equipment',
    'workOrderDetail.location': 'Location',
    'workOrderDetail.building': 'Building',
    'workOrderDetail.floor': 'Floor',
    'workOrderDetail.room': 'Room',
    'workOrderDetail.activity': 'Activity',
    'workOrderDetail.noCommentsYet': 'No comments yet',
    'workOrderDetail.unknownUser': 'Unknown User',
    'workOrderDetail.completionDetails': 'Completion Details',
    'workOrderDetail.completedBy': 'Completed By',
    'workOrderDetail.partsReplaced': 'Parts Replaced',
    'workOrderDetail.partsCost': 'Parts Cost',
    'workOrderDetail.laborCost': 'Labor Cost',
    'workOrderDetail.totalCost': 'Total Cost',
    'workOrderDetail.actualHours': 'Actual Hours',
    'workOrderDetail.completionNotes': 'Completion Notes',
    'workOrderDetail.quickActions': 'Quick Actions',
    'workOrderDetail.reassignTitle': 'Reassign Work Order',
    'workOrderDetail.assignTo': 'Assign to',
    'workOrderDetail.unassigned': 'Unassigned',
    'workOrderDetail.completeWorkOrder': 'Complete Work Order',
    'workOrderDetail.technicianName': 'Technician name',
    'workOrderDetail.partsReplacedPlaceholder': 'e.g.: Motor bearing, Transmission belt, Oil filter...',
    'workOrderDetail.partsDescription': 'Describe the parts that were replaced during this maintenance',
    'workOrderDetail.selectFromInventory': 'Select from Inventory',
    'workOrderDetail.selectedParts': 'Selected Parts',
    'workOrderDetail.quantity': 'Qty',
    'workOrderDetail.uploadCompletionPhoto': 'Upload Completion Photo',
    'workOrderDetail.takePhoto': 'Take Photo',
    'workOrderDetail.uploadFromGallery': 'Upload from Gallery',
    'workOrderDetail.maxFileSize': 'PNG, JPG, GIF up to 5MB',
    'workOrderDetail.completionNotesPlaceholder': 'Any additional notes about the work performed...',
    'workOrderDetail.markAsComplete': 'Mark as Complete',
    'workOrderDetail.uploading': 'Uploading...',
    'workOrderDetail.uploadedBy': 'Uploaded by',
  },
  
  ro: {
    // Navigation
    'nav.dashboard': 'Panou de control',
    'nav.scanQR': 'Scanare QR',
    'nav.equipment': 'Echipamente',
    'nav.locations': 'Locații',
    'nav.vehicles': 'Mașini',
    'nav.workOrders': 'Reparatii de efectuat',
    'nav.schedules': 'Mentenanță preventivă',
    'nav.checklists': 'Liste de Verificare',
    'nav.procedures': 'Proceduri',
    'nav.reports': 'Rapoarte',
    'nav.partsInventory': 'Inventar Piese',
    'nav.manual': 'Manual de Utilizare',
    'nav.users': 'Utilizatori',
    'nav.settings': 'Setări',
    'nav.logout': 'Deconectare',
    
    // Common
    'common.search': 'Căutare',
    'common.filter': 'Filtrare',
    'common.add': 'Adaugă',
    'common.edit': 'Modifică',
    'common.delete': 'Șterge',
    'common.save': 'Salvează',
    'common.cancel': 'Anulează',
    'common.close': 'Închide',
    'common.back': 'Înapoi',
    'common.next': 'Următorul',
    'common.previous': 'Anterior',
    'common.loading': 'Se încarcă...',
    'common.actions': 'Acțiuni',
    'common.view': 'Vizualizare',
    'common.create': 'Creează',
    'common.update': 'Actualizează',
    'common.name': 'Nume',
    'common.description': 'Descriere',
    'common.status': 'Status',
    'common.date': 'Dată',
    'common.total': 'Total',
    'common.all': 'Toate',
    'common.created': 'Creat',
    'common.noResults': 'Nu s-au găsit rezultate',
    
    // Equipment
    'equipment.title': 'Echipamente',
    'equipment.subtitle': 'echipamente totale',
    'equipment.add': 'Adaugă Echipament',
    'equipment.import': 'Importă Excel',
    'equipment.inventoryNumber': 'Nr. Inventar',
    'equipment.name': 'Nume',
    'equipment.brand': 'Marcă',
    'equipment.model': 'Model',
    'equipment.serialNumber': 'Număr Serie',
    'equipment.location': 'Locație',
    'equipment.purchaseDate': 'Data Achiziției',
    'equipment.status': 'Status',
    'equipment.operational': 'Operațional',
    'equipment.maintenance': 'Întreținere',
    'equipment.retired': 'Retras',
    'equipment.details': 'Detalii',
    'equipment.noEquipment': 'Nu s-au găsit echipamente',
    'equipment.searchPlaceholder': 'Căutare echipamente după nume, număr serie sau model...',
    
    // Work Orders
    'workOrders.title': 'Reparații de efectuat',
    'workOrders.subtitle': 'Gestionează reparațiile',
    'workOrders.new': 'Raportare defect',
    'workOrders.all': 'Toate Reparațiile',
    'workOrders.open': 'Deschise',
    'workOrders.inProgress': 'În Progres',
    'workOrders.onHold': 'În Așteptare',
    'workOrders.completed': 'Finalizate',
    'workOrders.cancelled': 'Anulate',
    'workOrders.priority': 'Prioritate',
    'workOrders.low': 'Scăzută',
    'workOrders.medium': 'Medie',
    'workOrders.high': 'Mare',
    'workOrders.critical': 'Critică',
    'workOrders.searchPlaceholder': 'Căutare reparații de efectuat...',
    'workOrders.allPriority': 'Toate Prioritățile',
    'workOrders.noWorkOrdersFound': 'Nu s-au găsit reparații de efectuat',
    'workOrders.noWorkOrdersYet': 'Încă nu există reparații de efectuat',
    'workOrders.tryAdjustingFilters': 'Încearcă să ajustezi filtrele',
    'workOrders.createFirstWorkOrder': 'Creează primul tău ordin de lucru pentru a începe',
    'workOrders.urgent': 'URGENT',
    'workOrders.highPriority': 'Prioritate Mare',
    'workOrders.equipment': 'Echipament:',
    'workOrders.location': 'Locație:',
    'workOrders.assignedTo': 'Asignat lui:',
    'workOrders.type': 'Tip',
    'workOrders.corrective': 'Corectiv',
    'workOrders.preventive': 'Preventiv',
    'workOrders.inspection': 'Inspecție',
    
    // Maintenance Schedules
    'schedules.title': 'Programări Întreținere',
    'schedules.subtitle': 'Gestionează programările de întreținere preventivă',
    'schedules.new': 'Programare Nouă',
    'schedules.all': 'Toate Programările',
    'schedules.active': 'Active',
    'schedules.overdue': 'Întârziate',
    'schedules.dueThisWeek': 'Săptămâna Aceasta',
    'schedules.frequency': 'Frecvență',
    'schedules.daily': 'Zilnic',
    'schedules.weekly': 'Săptămânal',
    'schedules.monthly': 'Lunar',
    'schedules.quarterly': 'Trimestrial',
    'schedules.semiannually': 'Semestrial',
    'schedules.annually': 'Anual',
    'schedules.nextDue': 'Următoarea Scadență',
    'schedules.lastCompleted': 'Ultima finalizare',
    'schedules.complete': 'Finalizează',
    'schedules.pause': 'Pauză',
    'schedules.resume': 'Reia',
    'schedules.showCompleted': 'Arată Doar Finalizate',
    'schedules.additionalFilters': 'Filtre Adiționale:',
    
    // Checklists
    'checklists.title': 'Șabloane Liste de Verificare',
    'checklists.subtitle': 'Creează și gestionează șabloane de liste reutilizabile',
    'checklists.new': 'Șablon Nou',
    'checklists.items': 'elemente de verificat',
    'checklists.noTemplates': 'Încă nu există șabloane',
    'checklists.createFirst': 'Creează primul tău șablon de listă pentru a-l folosi în programările de întreținere',
    'checklists.templateName': 'Nume Șablon',
    'checklists.addItem': 'Adaugă Element',
    
    // Procedures
    'procedures.title': 'Șabloane Proceduri',
    'procedures.subtitle': 'Creează și gestionează proceduri pas cu pas cu imagini',
    'procedures.new': 'Șablon Nou',
    'procedures.steps': 'pași',
    'procedures.noProcedures': 'Încă nu există șabloane',
    'procedures.createFirst': 'Creează primul tău șablon de procedură cu instrucțiuni pas cu pas',
    'procedures.addStep': 'Adaugă Pas',
    'procedures.hasImage': 'Are imagine',
    
    // Locations
    'locations.title': 'Locații',
    'locations.subtitle': 'Gestionează locațiile facilității',
    'locations.new': 'Locație Nouă',
    'locations.add': 'Adaugă Locație',
    'locations.building': 'Clădire',
    'locations.floor': 'Etaj',
    'locations.room': 'Cameră',
    'locations.address': 'Adresă',
    'locations.noLocations': 'Nu s-au găsit locații',
    'locations.noLocationsYet': 'Încă nu există locații',
    'locations.searchPlaceholder': 'Căutare locații...',
    'locations.tryAdjustingSearch': 'Încearcă să ajustezi căutarea',
    'locations.getStarted': 'Începe prin a adăuga prima ta locație',
    'locations.deleteConfirm': 'Sigur doriți să ștergeți',
    
    // Vehicles (Mașini)
    'vehicles.title': 'Mașini',
    'vehicles.subtitle': 'Gestionează mașinile firmei',
    'vehicles.new': 'Mașină Nouă',
    'vehicles.add': 'Adaugă Mașină',
    'vehicles.brand': 'Marcă',
    'vehicles.model': 'Model',
    'vehicles.registrationNumber': 'Număr Înmatriculare',
    'vehicles.vin': 'VIN',
    'vehicles.year': 'An Fabricație',
    'vehicles.color': 'Culoare',
    'vehicles.fuelType': 'Tip Combustibil',
    'vehicles.transmission': 'Transmisie',
    'vehicles.engineCapacity': 'Capacitate Cilindrică (cmc)',
    'vehicles.powerHP': 'Putere (CP)',
    'vehicles.currentMileage': 'Kilometraj Curent (km)',
    'vehicles.assignedTo': 'Asignat lui',
    'vehicles.department': 'Departament',
    'vehicles.purchaseDate': 'Data Achiziție',
    'vehicles.purchasePrice': 'Preț Achiziție',
    'vehicles.status': 'Status',
    'vehicles.operational': 'Operațional',
    'vehicles.inService': 'În Service',
    'vehicles.broken': 'Defect',
    'vehicles.sold': 'Vândut',
    'vehicles.retired': 'Retras',
    'vehicles.noVehicles': 'Nu s-au găsit mașini',
    'vehicles.searchPlaceholder': 'Căutare mașini...',
    'vehicles.documents': 'Documente',
    'vehicles.insurance': 'Asigurări',
    'vehicles.vignette': 'Roviniete',
    'vehicles.repairs': 'Reparații',
    'vehicles.rca': 'Asigurare RCA',
    'vehicles.casco': 'Asigurare CASCO',
    'vehicles.currentInsurance': 'Asigurare Curentă',
    'vehicles.insuranceHistory': 'Istoric Asigurări',
    'vehicles.currentVignette': 'Rovinieta Curentă',
    'vehicles.vignetteHistory': 'Istoric Roviniete',
    'vehicles.repairHistory': 'Istoric Reparații',
    'vehicles.addDocument': 'Adaugă Document',
    'vehicles.addInsurance': 'Adaugă Asigurare',
    'vehicles.addVignette': 'Adaugă Rovinieta',
    'vehicles.addRepair': 'Adaugă Reparație',
    'vehicles.documentType': 'Tip Document',
    'vehicles.insuranceCompany': 'Companie Asigurare',
    'vehicles.policyNumber': 'Număr Poliță',
    'vehicles.startDate': 'Data Început',
    'vehicles.endDate': 'Data Sfârșit',
    'vehicles.premiumAmount': 'Primă Asigurare',
    'vehicles.vignetteType': 'Tip Rovinieta',
    'vehicles.serialNumber': 'Număr Serie',
    'vehicles.country': 'Țară',
    'vehicles.price': 'Preț',
    'vehicles.repairType': 'Tip Reparație',
    'vehicles.repairDate': 'Data Reparației',
    'vehicles.serviceProvider': 'Furnizor Service',
    'vehicles.serviceLocation': 'Locație Service',
    'vehicles.mileageAtRepair': 'Kilometraj la Reparație',
    'vehicles.laborCost': 'Cost Manoperă',
    'vehicles.partsCost': 'Cost Piese',
    'vehicles.totalCost': 'Cost Total',
    'vehicles.benzina': 'Benzină',
    'vehicles.motorina': 'Motorină',
    'vehicles.electric': 'Electric',
    'vehicles.hibrid': 'Hibrid',
    'vehicles.gpl': 'GPL',
    'vehicles.manuala': 'Manuală',
    'vehicles.automata': 'Automată',
    'vehicles.preventiva': 'Preventivă',
    'vehicles.corectiva': 'Corectivă',
    'vehicles.accident': 'Accident',
    'vehicles.revizie': 'Revizie',
    'vehicles.certificat_inmatriculare': 'Certificat Înmatriculare',
    'vehicles.procura': 'Procură',
    'vehicles.contract_vanzare': 'Contract Vânzare',
    'vehicles.other': 'Altele',
    'vehicles.7_zile': '7 Zile',
    'vehicles.1_luna': '1 Lună',
    'vehicles.3_luni': '3 Luni',
    'vehicles.1_an': '1 An',
    'vehicles.active': 'Activ',
    'vehicles.expired': 'Expirat',
    'vehicles.noDocuments': 'Nu există documente',
    'vehicles.noInsurance': 'Nu există asigurări',
    'vehicles.noVignettes': 'Nu există roviniete',
    'vehicles.noRepairs': 'Nu există reparații',
    'vehicles.uploadFile': 'Încarcă Fișier',
    'vehicles.notes': 'Observații',
    'vehicles.issueDate': 'Data Emitere',
    'vehicles.expiryDate': 'Data Expirare',
    'vehicles.scheduled': 'Programat',
    'vehicles.inProgress': 'În Desfășurare',
    'vehicles.completed': 'Finalizat',
    'vehicles.cancelled': 'Anulat',
    'vehicles.expiresIn': 'Expiră în',
    'vehicles.expiredDaysAgo': 'Expirat',
    'vehicles.days': 'zile',
    
    // Dashboard
    'dashboard.title': 'Panou de Control',
    'dashboard.welcome': 'Bine ai revenit',
    'dashboard.overview': 'Prezentare Generală',
    'dashboard.recentActivity': 'Activitate Recentă',
    'dashboard.upcomingMaintenance': 'Întreținere Viitoare',
    
    // Settings
    'settings.title': 'Setări',
    'settings.language': 'Limbă',
    'settings.profile': 'Profil',
    'settings.notifications': 'Notificări',
    'settings.selectLanguage': 'Selectează Limba',
    'settings.english': 'Engleză',
    'settings.romanian': 'Română',
    
    // Work Order Detail
    'workOrderDetail.notFound': 'Comanda de lucru nu a fost găsită',
    'workOrderDetail.backToList': 'Înapoi la Reparații',
    'workOrderDetail.reassign': 'Reasignează',
    'workOrderDetail.edit': 'Modifică',
    'workOrderDetail.delete': 'Șterge',
    'workOrderDetail.description': 'Descriere',
    'workOrderDetail.noDescription': 'Nicio descriere furnizată',
    'workOrderDetail.photos': 'Fotografii',
    'workOrderDetail.reportPhoto': 'Fotografie Raportare',
    'workOrderDetail.issuePhoto': 'Fotografie Problemă',
    'workOrderDetail.completionPhoto': 'Fotografie Finalizare',
    'workOrderDetail.noPhotosYet': 'Încă nu sunt fotografii atașate',
    'workOrderDetail.equipment': 'Echipament',
    'workOrderDetail.location': 'Locație',
    'workOrderDetail.building': 'Clădire',
    'workOrderDetail.floor': 'Etaj',
    'workOrderDetail.room': 'Cameră',
    'workOrderDetail.activity': 'Activitate',
    'workOrderDetail.noCommentsYet': 'Încă nu există comentarii',
    'workOrderDetail.unknownUser': 'Utilizator Necunoscut',
    'workOrderDetail.completionDetails': 'Detalii Finalizare',
    'workOrderDetail.completedBy': 'Finalizat De',
    'workOrderDetail.partsReplaced': 'Piese Înlocuite',
    'workOrderDetail.partsCost': 'Cost Piese',
    'workOrderDetail.laborCost': 'Cost Manoperă',
    'workOrderDetail.totalCost': 'Cost Total',
    'workOrderDetail.actualHours': 'Ore Efective',
    'workOrderDetail.completionNotes': 'Note Finalizare',
    'workOrderDetail.quickActions': 'Acțiuni Rapide',
    'workOrderDetail.reassignTitle': 'Reasignează Comanda de Lucru',
    'workOrderDetail.assignTo': 'Asignează la',
    'workOrderDetail.unassigned': 'Neasignat',
    'workOrderDetail.completeWorkOrder': 'Finalizează Comanda de Lucru',
    'workOrderDetail.technicianName': 'Numele tehnicianului',
    'workOrderDetail.partsReplacedPlaceholder': 'ex: Rulment motor, Curea transmisie, Filtru ulei...',
    'workOrderDetail.partsDescription': 'Descrie piesele care au fost înlocuite în timpul acestei întrețineri',
    'workOrderDetail.selectFromInventory': 'Selectează din Inventar',
    'workOrderDetail.selectedParts': 'Piese Selectate',
    'workOrderDetail.quantity': 'Cant',
    'workOrderDetail.uploadCompletionPhoto': 'Încarcă Fotografie Finalizare',
    'workOrderDetail.takePhoto': 'Faceți Poză',
    'workOrderDetail.uploadFromGallery': 'Încarcă din Galerie',
    'workOrderDetail.maxFileSize': 'PNG, JPG, GIF până la 5MB',
    'workOrderDetail.completionNotesPlaceholder': 'Orice note suplimentare despre lucrul efectuat...',
    'workOrderDetail.markAsComplete': 'Marchează ca Finalizat',
    'workOrderDetail.uploading': 'Se încarcă...',
    'workOrderDetail.uploadedBy': 'Încărcat de',
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language')
    return saved || 'en'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const t = (key) => {
    return translations[language][key] || key
  }

  const value = {
    language,
    setLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
